# Language configuration for SocMed Downloader
# Supports: Indonesian (ID), English (EN), Japanese (JP)

LANGUAGES = {
    'id': {
        'app_title': 'SocMed Downloader',
        'subtitle': 'Download video & audio dari platform social media',
        'language_label': 'Bahasa:',
        'url_label': 'Masukkan URL Video/Audio:',
        'url_hint': 'TikTok, Instagram, Facebook, Twitter/X, atau platform lainnya',
        'format_label': 'Pilih Format:',
        'format_video': 'Video (MP4)',
        'format_audio': 'Audio (MP3)',
        'format_image': 'Gambar/Image (Terbatas)',
        'quality_label': 'Pilih Kualitas:',
        'quality_best': 'Terbaik (Otomatis)',
        'quality_1080p': '1080p (Full HD)',
        'quality_720p': '720p (HD)',
        'quality_480p': '480p (SD)',
        'quality_audio_best': 'Kualitas Terbaik',
        'quality_audio_320': '320 kbps (Kualitas Tinggi)',
        'quality_audio_192': '192 kbps (Standar)',
        'quality_audio_128': '128 kbps (Hemat Space)',
        'quality_image_best': 'Kualitas Terbaik (Original)',
        'cookies_label': 'Browser Cookies (untuk IG/FB):',
        'cookies_none': 'Tidak Pakai',
        'cookies_chrome': 'Google Chrome',
        'cookies_edge': 'Microsoft Edge',
        'cookies_firefox': 'Mozilla Firefox',
        'cookies_brave': 'Brave Browser',
        'download_button': 'Mulai Download',
        'clear_button': 'Bersihkan',
        'status_ready': 'Siap untuk download',
        'status_downloading': 'Sedang mendownload...',
        'status_processing': 'Sedang memproses dengan FFmpeg...',
        'status_success': 'Download berhasil!',
        'status_error': 'Error: {error}',
        'status_validating': 'Memvalidasi URL...',
        'progress_extracting': 'Mengekstrak informasi video...',
        'progress_downloading': 'Progress: {percent} | Speed: {speed}',
        'detected_platform': 'Platform: {platform}',
        'detected_title': 'Judul: {title}',
        'error_empty_url': 'URL tidak boleh kosong!',
        'error_invalid_url': 'URL tidak valid atau tidak didukung',
        'help_cookies': 'Gunakan cookies browser jika download Instagram/Facebook gagal (Error: Login required)',
        'platform_support': 'TikTok, Instagram, Facebook, Twitter/X & Platform Lainnya',
        'download_folder_label': '📁 Folder Download',
        'output_folder': 'File tersimpan di: {folder}',
        # Batch download
        'mode_label': 'Mode Download:',
        'mode_single': 'Single (1 link)',
        'mode_batch': 'Batch (Multiple links dari file)',
        'batch_file_label': 'Pilih File Batch:',
        'batch_file_button': 'Pilih File',
        'batch_add_url_label': '🔗 Tambah URL ke Daftar Batch (atau pilih file)',
        'batch_supported': 'Format: TXT, CSV, JSON (lihat contoh di folder test_samples/)',
        'batch_file_selected': 'File dipilih: {filename}',
        'batch_processing': 'Memproses {current}/{total} - {title}',
        'batch_complete': 'Batch selesai! {success} sukses, {failed} gagal dari {total} file',
        'batch_no_file': 'Silakan pilih file batch terlebih dahulu!',
        'batch_no_links': 'Tidak ada link valid ditemukan di file!',
        'batch_error_read': 'Error membaca file: {error}',
        # UI Labels
        'format_section_title': 'Format Download',
        'progress_section_title': 'Progress Download',
        'log_section_title': 'Log Download',
        'speed_label': 'Kecepatan',
        'eta_label': 'Estimasi Waktu',
        'ready_status': 'Siap',
    },
    'en': {
        'app_title': 'SocMed Downloader',
        'subtitle': 'Download videos & audio from social media platforms',
        'language_label': 'Language:',
        'url_label': 'Enter Video/Audio URL:',
        'url_hint': 'TikTok, Instagram, Facebook, Twitter/X, or other platforms',
        'format_label': 'Select Format:',
        'format_video': 'Video (MP4)',
        'format_audio': 'Audio (MP3)',
        'format_image': 'Image (Limited Support)',
        'quality_label': 'Select Quality:',
        'quality_best': 'Best (Automatic)',
        'quality_1080p': '1080p (Full HD)',
        'quality_720p': '720p (HD)',
        'quality_480p': '480p (SD)',
        'quality_audio_best': 'Best Quality',
        'quality_audio_320': '320 kbps (High Quality)',
        'quality_audio_192': '192 kbps (Standard)',
        'quality_audio_128': '128 kbps (Save Space)',
        'quality_image_best': 'Best Quality (Original)',
        'cookies_label': 'Browser Cookies (for IG/FB):',
        'cookies_none': 'None',
        'cookies_chrome': 'Google Chrome',
        'cookies_edge': 'Microsoft Edge',
        'cookies_firefox': 'Mozilla Firefox',
        'cookies_brave': 'Brave Browser',
        'download_button': 'Start Download',
        'clear_button': 'Clear',
        'status_ready': 'Ready to download',
        'status_downloading': 'Downloading...',
        'status_processing': 'Processing with FFmpeg...',
        'status_success': 'Download successful!',
        'status_error': 'Error: {error}',
        'status_validating': 'Validating URL...',
        'progress_extracting': 'Extracting video information...',
        'progress_downloading': 'Progress: {percent} | Speed: {speed}',
        'detected_platform': 'Platform: {platform}',
        'detected_title': 'Title: {title}',
        'error_empty_url': 'URL cannot be empty!',
        'error_invalid_url': 'Invalid or unsupported URL',
        'help_cookies': 'Use browser cookies if Instagram/Facebook download fails (Error: Login required)',
        'platform_support': 'TikTok, Instagram, Facebook, Twitter/X & More Platforms',
        'download_folder_label': '📁 Download Folder',
        'output_folder': 'File saved to: {folder}',
        # Batch download
        'mode_label': 'Download Mode:',
        'mode_single': 'Single (1 link)',
        'mode_batch': 'Batch (Multiple links from file)',
        'batch_file_label': 'Select Batch File:',
        'batch_file_button': 'Select File',
        'batch_add_url_label': '🔗 Add URL to Batch List (or select file)',
        'batch_supported': 'Formats: TXT, CSV, JSON (see examples in test_samples/ folder)',
        'batch_file_selected': 'File selected: {filename}',
        'batch_processing': 'Processing {current}/{total} - {title}',
        'batch_complete': 'Batch complete! {success} success, {failed} failed out of {total} files',
        'batch_no_file': 'Please select a batch file first!',
        'batch_no_links': 'No valid links found in file!',
        'batch_error_read': 'Error reading file: {error}',
        # UI Labels
        'format_section_title': 'Download Format',
        'progress_section_title': 'Download Progress',
        'log_section_title': 'Download Log',
        'speed_label': 'Speed',
        'eta_label': 'ETA',
        'ready_status': 'Ready',
    },
    'jp': {
        'app_title': 'SocMed Downloader',
        'subtitle': 'ソーシャルメディアから動画・音声をダウンロード',
        'language_label': '言語:',
        'url_label': '動画/音声のURLを入力:',
        'url_hint': 'TikTok, Instagram, Facebook, Twitter/X、または他のプラットフォーム',
        'format_label': 'フォーマットを選択:',
        'format_video': 'ビデオ (MP4)',
        'format_audio': 'オーディオ (MP3)',
        'format_image': '画像 (制限あり)',
        'quality_label': '品質を選択:',
        'quality_best': '最高（自動）',
        'quality_1080p': '1080p (フルHD)',
        'quality_720p': '720p (HD)',
        'quality_480p': '480p (SD)',
        'quality_audio_best': '最高品質',
        'quality_audio_320': '320 kbps（高品質）',
        'quality_audio_192': '192 kbps（標準）',
        'quality_audio_128': '128 kbps（容量節約）',
        'quality_image_best': '最高品質（オリジナル）',
        'cookies_label': 'ブラウザCookie (IG/FB用):',
        'cookies_none': 'なし',
        'cookies_chrome': 'Google Chrome',
        'cookies_edge': 'Microsoft Edge',
        'cookies_firefox': 'Mozilla Firefox',
        'cookies_brave': 'Brave Browser',
        'download_button': 'ダウンロード開始',
        'clear_button': 'クリア',
        'status_ready': 'ダウンロード準備完了',
        'status_downloading': 'ダウンロード中...',
        'status_processing': 'FFmpegで処理中...',
        'status_success': 'ダウンロード成功！',
        'status_error': 'エラー: {error}',
        'status_validating': 'URLを検証中...',
        'progress_extracting': '動画情報を抽出中...',
        'progress_downloading': '進捗: {percent} | 速度: {speed}',
        'detected_platform': 'プラットフォーム: {platform}',
        'detected_title': 'タイトル: {title}',
        'error_empty_url': 'URLを入力してください！',
        'error_invalid_url': '無効またはサポートされていないURL',
        'help_cookies': 'Instagram/Facebookのダウンロードが失敗する場合はブラウザCookieを使用（エラー: ログインが必要）',
        'platform_support': 'TikTok, Instagram, Facebook, Twitter/X & その他',
        'download_folder_label': '📁 ダウンロードフォルダ',
        'output_folder': 'ファイル保存先: {folder}',
        # Batch download
        'mode_label': 'ダウンロードモード:',
        'mode_single': 'シングル (1リンク)',
        'mode_batch': 'バッチ (ファイルから複数リンク)',
        'batch_file_label': 'バッチファイルを選択:',
        'batch_file_button': 'ファイル選択',
        'batch_add_url_label': '🔗 バッチリストにURLを追加 (またはファイル選択)',
        'batch_supported': '形式: TXT, CSV, JSON (test_samples/フォルダにサンプルあり)',
        'batch_file_selected': '選択されたファイル: {filename}',
        'batch_processing': '処理中 {current}/{total} - {title}',
        'batch_complete': 'バッチ完了！ {success} 成功、{failed} 失敗 / {total} ファイル',
        'batch_no_file': 'バッチファイルを選択してください！',
        'batch_no_links': 'ファイルに有効なリンクが見つかりません！',
        'batch_error_read': 'ファイル読み込みエラー: {error}',
        # UI Labels
        'format_section_title': 'ダウンロード形式',
        'progress_section_title': 'ダウンロード進行状況',
        'log_section_title': 'ダウンロードログ',
        'speed_label': '速度',
        'eta_label': '予想時間',
        'ready_status': '準備完了',
    }
}

def get_text(lang_code, key, **kwargs):
    """Get translated text for given language and key"""
    lang = LANGUAGES.get(lang_code, LANGUAGES['id'])
    text = lang.get(key, LANGUAGES['id'].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text
